- category: "Weitere Websites"
  description: "Unsere zentralen Hubs und Landing Pages."
  items:
    - title: "STORB Consulting"
      url: "https://storbconsulting.kesug.com/"
      icon: "language"
      type: "material"
      description: "Offizielle Unternehmenswebseite."
    - title: "STORB Travel Consulting"
      url: "https://storbtravel.wordpress.com/"
      icon: "public"
      type: "material"
      description: "Reiseberatung und Destinationen."
    - title: "STORB Business Hub"
      url: "https://storbconsulting.kesug.com/"
      icon: "business_center"
      type: "material"
      description: "Zentraler Zugang zu unseren Business-Services."
    - title: "Prinzipal-Mode"
      url: "https://prinzipal-mode.de/"
      icon: "checkroom" # Alternativ shopping_bag
      type: "material"
      description: "Fashion und Mode." 
    - title: "stc music"
      url: "https://sites.google.com/view/stc-music/home"
      icon: "music_note"
      type: "material"
      description: "Musikprojekte und Veröffentlichungen."

- category: "Handel & Blogs"
  description: "Online-Shops und redaktionelle Inhalte."
  items:
    - title: "Amazon – STORB"
      url: "https://www.amazon.de/sp?ie=UTF8&seller=A3RBQE296XWBLJ"
      icon: "shopping_cart"
      type: "material"
      description: "Unser Amazon Händlerprofil."
    - title: "Blogspot – stc-weblog"
      url: "https://stc-weblog.blogspot.com/"
      icon: "rss_feed"
      type: "material"
      description: "News, Updates und Artikel."

- category: "Musik & Kreativität"
  description: "Streaming, Code und Fotografie."
  items:
    - title: "Deezer"
      url: "https://www.deezer.com/de/artist/11667829"
      icon: "headphones"
      type: "material"
      description: "Christian Storb auf Deezer."
    - title: "Spotify"
      url: "https://open.spotify.com/intl-de/artist/2hnGbPtHIj3L3xWY6g41l3"
      icon: "headphones"
      type: "material"
      description: "Christian Storb auf Spotify."
    - title: "jsFiddle"
      url: "https://jsfiddle.net/u/chstorb/fiddles/"
      icon: "code"
      type: "material"
      description: "Code Snippets und Experimente."
    - title: "Pixabay"
      url: "https://pixabay.com/users/stcpictures-11034844/"
      icon: "photo_camera"
      type: "material"
      description: "Lizenzfreie Bilder von stcpictures."

- category: "Social Media & Netzwerke"
  description: "Vernetzen Sie sich mit uns."
  items:
    - title: "LinkedIn"
      url: "https://www.linkedin.com/in/christian-storb-326249aa"
      icon: "linkedin"
      type: "brand"
      description: "Berufliches Netzwerk."
    - title: "Instagram"
      url: "https://www.instagram.com/storbconsulting"
      icon: "instagram"
      type: "brand"
      description: "Visuelle Einblicke und Stories."
    - title: "Twitter"
      url: "https://twitter.com/ChristianStorb"
      icon: "twitter"
      type: "brand"
      description: "Kurznachrichten und Updates."
    - title: "YouTube"
      url: "https://www.youtube.com/@christianstorb"
      icon: "youtube"
      type: "brand"
      description: "Videos und Kanäle."
    - title: "Stack Overflow"
      url: "https://stackoverflow.com/users/4441032/christian-storb"
      icon: "stackoverflow"
      type: "brand"
      description: "Entwickler-Community Profil."
