- category: "Weitere Websites"
  description: "Unsere zentralen Hubs und Landing Pages."
  items:
    - title: "Christian Storb - STORB Consulting"
      url: "https://storbconsulting.wordpress.com/"
      icon: "language"
      type: "material"
      description: "Offizielle Unternehmenswebseite."
    - title: "Christian Storb - STORB Travel Consulting"
      url: "https://storbtravel.wordpress.com/"
      icon: "public"
      type: "material"
      description: "Reiseberatung und Destinationen."
    - title: "Christian Storb - STORB Business Hub"
      url: "https://stcbusinesshub.wordpress.com/"
      icon: "business_center"
      type: "material"
      description: "Zentraler Zugang zu unseren Business-Services."
    - title: "Prinzipal-Mode"
      url: "https://prinzipal-mode.de/"
      icon: "checkroom" # Alternativ shopping_bag
      type: "material"
      description: "Fashion & Co." 
    - title: "Christian Storb - STORB Music"
      url: "https://sites.google.com/view/stc-music/home"
      icon: "music_note"
      type: "material"
      description: "Musikprojekte und Veröffentlichungen."

- category: "Handel & Blogs"
  description: "Online-Shops und redaktionelle Inhalte."
  items:
    - title: "STORB-SHOP - Amazon"
      url: "https://www.amazon.de/s?me=A3RBQE296XWBLJ"
      icon: "shopping_cart"
      type: "material"
      description: "Unser Amazon-Shop."
    - title: "STORB-SHOP - eBay"
      url: "https://www.ebay.de/usr/storb-shop"
      icon: "shopping_cart"
      type: "material"
      description: "Unser eBay-Shop."      
    - title: "STORB Consulting - Blogspot"
      url: "https://chstorb.blogspot.com"
      icon: "rss_feed"
      type: "material"
      description: "News, Updates und Artikel."
    - title: "STORB Travel Consulting - Blogspot"
      url: "https://stc-travel-consulting.blogspot.com/"
      icon: "public"
      type: "material"
      description: "Reiseberatung und Destinationen."

- category: "Musik & Kreativität"
  description: "Streaming, Code und Fotografie."
  items:
    - title: "Christian Storb - Amazon Music"
      url: "https://www.amazon.com/music/player/artists/B01MS5O30Z/christian-storb"
      icon: "headphones"
      type: "material"
      description: "Christian Storb auf Amazon Music."      
    - title: "Christian Storb - Apple Music"
      url: "https://music.apple.com/de/artist/christian-storb/1193224684"
      icon: "headphones"
      type: "material"
      description: "Christian Storb auf Apple Music."
    - title: "Christian Storb - Boomplay"
      url: "https://www.boomplay.com/albums/68369545"
      icon: "headphones"
      type: "material"
      description: "Christian Storb auf Boomplay."      
    - title: "Christian Storb - Deezer"
      url: "https://www.deezer.com/de/artist/11667829"
      icon: "headphones"
      type: "material"
      description: "Christian Storb auf Deezer."
    - title: "Christian Storb - GitHub"
      url: "https://github.com/chstorb"
      icon: "code"
      type: "material"
      description: "Code-Repositories und Projekte"
    - title: "Christian Storb - Google for Developers"
      url: "https://developers.google.com/profile/u/christian-storb"
      icon: "code"
      type: "material"
      description: "Profile auf Google for Developers"
    - title: "Christian Storb - SHAZAM"
      url: "https://www.shazam.com/artist/*/1657370575"
      icon: "headphones"
      type: "material"
      description: "Christian Storb auf SHAZAM."
    - title: "Christian Storb - Spotify"
      url: "https://open.spotify.com/intl-de/artist/2hnGbPtHIj3L3xWY6g41l3"
      icon: "headphones"
      type: "material"
      description: "Christian Storb auf Spotify."
    - title: "Christian Storb - jsFiddle"
      url: "https://jsfiddle.net/u/chstorb/fiddles/"
      icon: "code"
      type: "material"
      description: "Code Snippets und Experimente."
    - title: "STC Pictures - Pixabay"
      url: "https://pixabay.com/users/stcpictures-11034844/"
      icon: "photo_camera"
      type: "material"
      description: "Lizenzfreie Bilder von Christian Storb."
    - title: "Christian Storb - YouTube"
      url: "https://www.youtube.com/@christianstorb"
      icon: "youtube"
      type: "brand"
      description: "Videos und Kanäle."      
    - title: "Christian Storb - Thema auf YouTube"
      url: "https://www.youtube.com/channel/UCiwOXcnDgZEEiz2DpiRNUFw"
      icon: "youtube"
      type: "brand"
      description: "Thema auf YouTube."

- category: "Social Media & Netzwerke"
  description: "Vernetzen Sie sich mit uns."
  items:
    - title: "Christian Storb - Prog.AI"
      url: "https://getprog.ai/profile/10462545"
      icon: "chevron_right"
      type: "material"
      description: "Berufliches Netzwerk."
    - title: "Christian Storb - LinkedIn"
      url: "https://www.linkedin.com/in/christian-storb-326249aa/"
      icon: "linkedin"
      type: "brand"
      description: "Berufliches Netzwerk."      
    - title: "STORB Consulting - Facebook"
      url: "https://www.facebook.com/storb.christian/"
      icon: "face"
      type: "material"
      description: "Visuelle Einblicke und Stories." 
    - title: "STORB Consulting - Instagram"
      url: "https://www.instagram.com/storbconsulting"
      icon: "instagram"
      type: "brand"
      description: "Visuelle Einblicke und Stories."
    - title: "STORB Consulting - X"
      url: "https://twitter.com/ChristianStorb"
      icon: "twitter"
      type: "brand"
      description: "Kurznachrichten und Updates."
    - title: "Christian Storb - Stack Overflow"
      url: "https://stackoverflow.com/users/4441032/christian-storb"
      icon: "stackoverflow"
      type: "brand"
      description: "Entwickler-Community Profil."
    - title: "Christian Storb - about.me"
      url: "https://about.me/christianstorb"
      icon: "about.me"
      type: "brand"
      description: "Persönliche Informationen."